[Definition]
failregex = ^.*\bCan't find user \[[^\]]+\] from <HOST>\s*$
            ^.*\bSIP auth failure .* from <HOST>.*$
            ^.*\bRegistration from .+ failed .* from <HOST>.*$
            ^.*\bsofia\.c:\d+\s+sofia/external/\S+\s+receiving invite from <HOST>:\d+.*$
ignoreregex =
