[Definition]
failregex = ^.*\bCan't find user \[[^\]]+\] from <HOST>\s*$
            ^.*\bSIP auth failure .* from <HOST>.*$
            ^.*\bRegistration from .+ failed .* from <HOST>.*$
ignoreregex =
