create table if not exists call_browser_media_stats (
  call_id uuid primary key references calls(id) on delete cascade,
  schema_version integer not null check (schema_version = 1),
  started_at timestamptz not null,
  ended_at timestamptz not null,
  captured_at timestamptz not null default now(),
  sample_count integer not null check (sample_count > 0),
  microphone_sample_rate integer,
  microphone_sample_size integer,
  microphone_channel_count integer,
  microphone_echo_cancellation boolean,
  microphone_noise_suppression boolean,
  microphone_auto_gain_control boolean,
  microphone_latency_seconds double precision,
  inbound_codec text,
  inbound_packets_received bigint,
  inbound_packets_lost bigint,
  inbound_packets_discarded bigint,
  inbound_jitter_seconds_max double precision,
  inbound_jitter_buffer_delay_seconds double precision,
  inbound_jitter_buffer_emitted_count bigint,
  inbound_concealed_samples bigint,
  inbound_total_samples_received bigint,
  inbound_concealment_events bigint,
  inbound_audio_energy double precision,
  inbound_audio_duration_seconds double precision,
  outbound_codec text,
  outbound_packets_sent bigint,
  outbound_bytes_sent bigint,
  outbound_remote_packets_lost bigint,
  outbound_remote_jitter_seconds_max double precision,
  outbound_round_trip_time_seconds_max double precision,
  local_candidate_type text,
  remote_candidate_type text,
  transport_protocol text,
  relay_protocol text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at >= started_at)
);

create index if not exists call_browser_media_stats_captured_at_idx
  on call_browser_media_stats(captured_at desc);
