[freeswitch-sip-scan]
enabled = true
filter = freeswitch-sip-scan
logpath = /var/log/freeswitch/freeswitch.log
backend = auto
maxretry = 2
findtime = 30m
bantime = 12h
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 7d
port = 5060,5080,5081,7443
protocol = all
banaction = iptables-allports
