[freeswitch-sip-scan]
enabled = true
filter = freeswitch-sip-scan
logpath = /var/log/freeswitch/freeswitch.log
backend = auto
maxretry = 3
findtime = 10m
bantime = 1h
port = 5060,5080,5081,7443
protocol = all
banaction = iptables-allports
